# Generated by Django 4.0.5 on 2022-11-22 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_remove_follow_followers_follow_followers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='likes',
        ),
        migrations.AlterField(
            model_name='likes',
            name='liked_user',
            field=models.ManyToManyField(blank=True, related_name='likes_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
