# Generated by Django 4.0.5 on 2022-11-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_data_likes_alter_likes_liked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
