# Generated by Django 4.0.5 on 2022-11-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_data_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked_content',
            field=models.IntegerField(),
        ),
    ]
